apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - charts/crds/crds/monitoring.grafana.com_podlogs.yaml
  - templates/configmap.yaml
  - templates/controllers/daemonset.yaml
  - templates/rbac.yaml
  - templates/service.yaml
  - templates/serviceaccount.yaml
