apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/gateway.nginx.org_authenticationfilters.yaml
  - crds/gateway.nginx.org_clientsettingspolicies.yaml
  - crds/gateway.nginx.org_nginxgateways.yaml
  - crds/gateway.nginx.org_nginxproxies.yaml
  - crds/gateway.nginx.org_observabilitypolicies.yaml
  - crds/gateway.nginx.org_proxysettingspolicies.yaml
  - crds/gateway.nginx.org_ratelimitpolicies.yaml
  - crds/gateway.nginx.org_snippetsfilters.yaml
  - crds/gateway.nginx.org_snippetspolicies.yaml
  - crds/gateway.nginx.org_upstreamsettingspolicies.yaml
  - templates/certs-job.yaml
  - templates/deployment.yaml
  - templates/gatewayclass.yaml
  - templates/nginxgateway.yaml
  - templates/nginxproxy.yaml
  - templates/rbac.yaml
  - templates/service.yaml
  - templates/serviceaccount.yaml
