apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - charts/crds/crds/crd-alertmanagerconfigs.yaml
  - charts/crds/crds/crd-alertmanagers.yaml
  - charts/crds/crds/crd-podmonitors.yaml
  - charts/crds/crds/crd-probes.yaml
  - charts/crds/crds/crd-prometheusagents.yaml
  - charts/crds/crds/crd-prometheuses.yaml
  - charts/crds/crds/crd-prometheusrules.yaml
  - charts/crds/crds/crd-scrapeconfigs.yaml
  - charts/crds/crds/crd-servicemonitors.yaml
  - charts/crds/crds/crd-thanosrulers.yaml
  - charts/grafana/templates/clusterrole.yaml
  - charts/grafana/templates/clusterrolebinding.yaml
  - charts/grafana/templates/configmap-dashboard-provider.yaml
  - charts/grafana/templates/configmap.yaml
  - charts/grafana/templates/deployment.yaml
  - charts/grafana/templates/role.yaml
  - charts/grafana/templates/rolebinding.yaml
  - charts/grafana/templates/secret.yaml
  - charts/grafana/templates/service.yaml
  - charts/grafana/templates/serviceaccount.yaml
  - charts/grafana/templates/servicemonitor.yaml
  - charts/kube-state-metrics/templates/clusterrolebinding.yaml
  - charts/kube-state-metrics/templates/deployment.yaml
  - charts/kube-state-metrics/templates/role.yaml
  - charts/kube-state-metrics/templates/service.yaml
  - charts/kube-state-metrics/templates/serviceaccount.yaml
  - charts/kube-state-metrics/templates/servicemonitor.yaml
  - charts/prometheus-node-exporter/templates/daemonset.yaml
  - charts/prometheus-node-exporter/templates/service.yaml
  - charts/prometheus-node-exporter/templates/serviceaccount.yaml
  - charts/prometheus-node-exporter/templates/servicemonitor.yaml
  - templates/alertmanager/alertmanager.yaml
  - templates/alertmanager/secret.yaml
  - templates/alertmanager/service.yaml
  - templates/alertmanager/serviceaccount.yaml
  - templates/alertmanager/servicemonitor.yaml
  - templates/exporters/core-dns/service.yaml
  - templates/exporters/core-dns/servicemonitor.yaml
  - templates/exporters/kube-api-server/servicemonitor.yaml
  - templates/exporters/kube-controller-manager/service.yaml
  - templates/exporters/kube-controller-manager/servicemonitor.yaml
  - templates/exporters/kube-etcd/service.yaml
  - templates/exporters/kube-etcd/servicemonitor.yaml
  - templates/exporters/kube-proxy/service.yaml
  - templates/exporters/kube-proxy/servicemonitor.yaml
  - templates/exporters/kube-scheduler/service.yaml
  - templates/exporters/kube-scheduler/servicemonitor.yaml
  - templates/exporters/kubelet/servicemonitor.yaml
  - templates/grafana/configmaps-datasources.yaml
  - templates/grafana/dashboards-1.14/alertmanager-overview.yaml
  - templates/grafana/dashboards-1.14/apiserver.yaml
  - templates/grafana/dashboards-1.14/cluster-total.yaml
  - templates/grafana/dashboards-1.14/controller-manager.yaml
  - templates/grafana/dashboards-1.14/etcd.yaml
  - templates/grafana/dashboards-1.14/grafana-overview.yaml
  - templates/grafana/dashboards-1.14/k8s-coredns.yaml
  - templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
  - templates/grafana/dashboards-1.14/k8s-resources-multicluster.yaml
  - templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
  - templates/grafana/dashboards-1.14/k8s-resources-node.yaml
  - templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
  - templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
  - templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
  - templates/grafana/dashboards-1.14/kubelet.yaml
  - templates/grafana/dashboards-1.14/namespace-by-pod.yaml
  - templates/grafana/dashboards-1.14/namespace-by-workload.yaml
  - templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
  - templates/grafana/dashboards-1.14/node-rsrc-use.yaml
  - templates/grafana/dashboards-1.14/nodes-aix.yaml
  - templates/grafana/dashboards-1.14/nodes-darwin.yaml
  - templates/grafana/dashboards-1.14/nodes.yaml
  - templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
  - templates/grafana/dashboards-1.14/pod-total.yaml
  - templates/grafana/dashboards-1.14/prometheus.yaml
  - templates/grafana/dashboards-1.14/proxy.yaml
  - templates/grafana/dashboards-1.14/scheduler.yaml
  - templates/grafana/dashboards-1.14/workload-total.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/clusterrolebinding.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/role.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/rolebinding.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
  - templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
  - templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
  - templates/prometheus-operator/clusterrole.yaml
  - templates/prometheus-operator/clusterrolebinding.yaml
  - templates/prometheus-operator/deployment.yaml
  - templates/prometheus-operator/service.yaml
  - templates/prometheus-operator/serviceaccount.yaml
  - templates/prometheus-operator/servicemonitor.yaml
  - templates/prometheus/clusterrole.yaml
  - templates/prometheus/clusterrolebinding.yaml
  - templates/prometheus/prometheus.yaml
  - templates/prometheus/rules-1.14/alertmanager.rules.yaml
  - templates/prometheus/rules-1.14/config-reloaders.yaml
  - templates/prometheus/rules-1.14/etcd.yaml
  - templates/prometheus/rules-1.14/general.rules.yaml
  - templates/prometheus/rules-1.14/k8s.rules.container_cpu_usage_seconds_total.yaml
  - templates/prometheus/rules-1.14/k8s.rules.container_memory_cache.yaml
  - templates/prometheus/rules-1.14/k8s.rules.container_memory_rss.yaml
  - templates/prometheus/rules-1.14/k8s.rules.container_memory_swap.yaml
  - templates/prometheus/rules-1.14/k8s.rules.container_memory_working_set_bytes.yaml
  - templates/prometheus/rules-1.14/k8s.rules.container_resource.yaml
  - templates/prometheus/rules-1.14/k8s.rules.pod_owner.yaml
  - templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml
  - templates/prometheus/rules-1.14/kube-apiserver-burnrate.rules.yaml
  - templates/prometheus/rules-1.14/kube-apiserver-histogram.rules.yaml
  - templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
  - templates/prometheus/rules-1.14/kube-prometheus-general.rules.yaml
  - templates/prometheus/rules-1.14/kube-prometheus-node-recording.rules.yaml
  - templates/prometheus/rules-1.14/kube-scheduler.rules.yaml
  - templates/prometheus/rules-1.14/kube-state-metrics.yaml
  - templates/prometheus/rules-1.14/kubelet.rules.yaml
  - templates/prometheus/rules-1.14/kubernetes-apps.yaml
  - templates/prometheus/rules-1.14/kubernetes-resources.yaml
  - templates/prometheus/rules-1.14/kubernetes-storage.yaml
  - templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  - templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
  - templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml
  - templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  - templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
  - templates/prometheus/rules-1.14/kubernetes-system.yaml
  - templates/prometheus/rules-1.14/node-exporter.rules.yaml
  - templates/prometheus/rules-1.14/node-exporter.yaml
  - templates/prometheus/rules-1.14/node-network.yaml
  - templates/prometheus/rules-1.14/node.rules.yaml
  - templates/prometheus/rules-1.14/prometheus-operator.yaml
  - templates/prometheus/rules-1.14/prometheus.yaml
  - templates/prometheus/service.yaml
  - templates/prometheus/serviceaccount.yaml
  - templates/prometheus/servicemonitor.yaml
