grafana:
  additionalDataSources:
  - access: proxy
    editable: false
    headers:
      X-Scope-OrgID: "1"
    jsonData:
      maxLines: 1000
      tlsSkipVerify: true
    name: loki
    orgId: 1
    type: loki
    url: http://loki-gateway.default.svc.cluster.local
    version: 1
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      serve_from_sub_path: true