---
# Source: nginx-gateway-fabric/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway-fabric
  namespace: gateway-api
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.4.2
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginx-gateway-fabric
    app.kubernetes.io/version: "2.4.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
      app.kubernetes.io/instance: nginx-gateway-fabric
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-gateway-fabric
        app.kubernetes.io/instance: nginx-gateway-fabric
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - controller
        - --gateway-ctlr-name=gateway.nginx.org/nginx-gateway-controller
        - --gatewayclass=nginx
        - --config=nginx-gateway-fabric-config
        - --service=nginx-gateway-fabric
        - --agent-tls-secret=agent-tls
        - --metrics-port=9113
        - --health-port=8081
        - --leader-election-lock-name=nginx-gateway-fabric-leader-election
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/instance']
        - name: IMAGE_NAME
          value: ghcr.io/nginx/nginx-gateway-fabric:2.4.2
        image: ghcr.io/nginx/nginx-gateway-fabric:2.4.2
        imagePullPolicy: IfNotPresent
        name: nginx-gateway
        ports:
        - name: agent-grpc
          containerPort: 8443
        - name: metrics
          containerPort: 9113
        - name: health
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 3
          periodSeconds: 1
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-agent-tls
          mountPath: /var/run/secrets/ngf
      terminationGracePeriodSeconds: 30
      serviceAccountName: nginx-gateway-fabric
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      volumes:
      - name: nginx-agent-tls
        secret:
          secretName: server-tls
