# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

resources:
- ../../../manifests/alloy
- ../../../manifests/kube-prometheus-stack
- ../../../manifests/loki
- ../../../manifests/cloudnative-pg
- ../../../manifests/gateway-api # Depends on nginx-gateway-fabric
- ../../../manifests/nginx-gateway-fabric

labels:
- pairs:
    cluster: dnl-loc-obs-001

# TODO: Test updating application image
# images:
# - name: xxx
#   newTag: v0.1.2