# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

resources:
- ../../../applications/alloy
- ../../../applications/kube-prometheus-stack
- ../../../applications/loki
- ../../../applications/cloudnative-pg
- ../../../applications/gateway-api # Depends on nginx-gateway-fabric
- ../../../applications/nginx-gateway-fabric

labels:
- pairs:
    cluster: dnl-loc-obs-001

# TODO: Test updating application image
# images:
# - name: xxx
#   newTag: v0.1.2